version: '3.7'

networks:
  my-net:
    external: true

volumes:
  psql_storage:
    external: true
  nginx_secrets:
    external: true

services:

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    networks:
      - my-net
    ports:
      - '5437:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - psql_storage:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:12.0.0
    container_name: keycloak
    networks:
      - my-net
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: SOMETHING_LONG_AND_SECURE
      KEYCLOAK_HTTP_PORT: 8080
      PROXY_ADDRESS_FORWARDING: 'true'
      # JDBC_PARAMS: 'connectTimeout=30'
    # ports:
    #   - 8080:8080
    depends_on:
      - postgres
    healthcheck:
      test: curl --fail -s http://localhost:8080 || exit 1
      start_period: 30s
      interval: 15s
      timeout: 15s
      retries: 5

  webserver:
    image: jonasal/nginx-certbot:latest
    container_name: webserver
    networks:
      - my-net
    environment:
      CERTBOT_EMAIL: YOUR_EMAIL
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - keycloak
    healthcheck:
      test: curl --fail -s http://localhost:80 || exit 1
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 5
