services:
  caddy:
    image: caddy:2.4.3-alpine
    networks:
      - minio-net
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  miniod:
    image: minio/minio
    networks:
      - minio-net
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /mnt/data --console-address :9001
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: yourusername
      MINIO_ROOT_PASSWORD: yourverylongandsecurepasscode

networks:
  minio-net:
